version: "3.8"

services:
  postgres:
    container_name: dev_postgres_container
    image: postgres:latest
    ports:
      - 5666:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./db:/var/lib/postgresql/data/

  redis:
    container_name: dev_redis_container
    image: redis:latest
    ports:
      - 6666:6379
    environment:
      REDIS_PASSWORD: password
    volumes:
      - ./redis:/data

  maildev:
    container_name: dev_maildev_container
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "1025:25"
